### ISSUE TITLE
duck.obj在哪儿呢？

### ISSUE THREAD

**Issue by sume-cn** [Shadowithin/OpenCVRayTracer#1]
cannot find this file

**Comment by sume-cn** [comment]
got it!:
https://raw.githubusercontent.com/cocosh03/TP1RDV/master/duck.obj

**Comment by Shadowithin** [comment]
https://github.com/ssloy/tinyraytracer/tree/homework_assignment
用的是这个repo的鸭子




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Shadowithin/OpenCVRayTracer"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月17日(星期四) 晚上7:16
收件人:&nbsp;"Shadowithin/OpenCVRayTracer"<OpenCVRayTracer@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [Shadowithin/OpenCVRayTracer] duck.obj在哪儿呢？ (#1)





 
Closed #1.
