### ISSUE TITLE
reflect depth not effective

### ISSUE THREAD

**Issue by sume-cn** [Shadowithin/OpenCVRayTracer#2]
没有多次反射

**Comment by Shadowithin** [comment]
我印象中应该是有的，在cast_ray函数里，是用递归实现的




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "sume-cn"<notifications@github.com&gt;; 
发送时间: 2020年12月18日(星期五) 下午4:37
收件人: "Shadowithin/OpenCVRayTracer"<OpenCVRayTracer@noreply.github.com&gt;; 
抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 
主题: [Shadowithin/OpenCVRayTracer] reflect depth not effective (#2)





 
没有多次反射

**Comment by sume-cn** [comment]
哦sorry，改代码后的笔误
